from_latest_tag = false
ignore_merge_commits = false
disable_changelog = false
disable_bump_commit = false
generate_mono_repository_global_tag = true
branch_whitelist = ["main"]
skip_ci = "[skip-ci]"
skip_untracked = false
pre_bump_hooks = []
post_bump_hooks = []
pre_package_bump_hooks = []
post_package_bump_hooks = []

[git_hooks.commit-msg]
script = """#!/bin/sh
set -e
cog verify --file $1
cog check
"""

[changelog]
path = "CHANGELOG.md"
template = "full_hash"
authors = [
    { username = "tommy-donavon", signature = "Tommy Donavon" }
]

