{ self, pkgs, ... }:
let
  inherit (self.lib.system) systemTernary;

  sudoers = systemTernary pkgs "@wheel" "@admin";
in
{
  nix.settings = {
    experimental-features = [
      "nix-command"
      "flakes"
    ];
    http-connections = 50;
    log-lines = 50;
    warn-dirty = false;

    allow-import-from-derivation = true;
    auto-optimise-store = false;

    allowed-users = [ sudoers ];
    trusted-users = [ sudoers ];

    keep-derivations = true;
    keep-going = true;
    keep-outputs = true;
    max-jobs = "auto";

    # Large builds apparently fail due to an issue with darwin:
    # https://github.com/NixOS/nix/issues/4119
    sandbox = pkgs.stdenv.isLinux;

    use-xdg-base-directories = true;

    # NOTE: This configuration was originally generated by the nix-installer so I'm adding it here in
    # case it becomes important.
    extra-nix-path = "nixpkgs=flake:nixpkgs";

    substituters = [
      "https://nix-community.cachix.org"
    ];

    trusted-public-keys = [
      "nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs="
    ];
  };
}
